### Part 1: Theoretical Question

In [ ]:
Q1.What are the different data structures used in Tensorflow?. Give some examples?

In [ ]:
TensorFlow is a framework for building and executing computational graphs, which are structures that represent how data flows across
a series of processing nodes. Each node in the graph performs a mathematical operation, and each edge or connection between nodes 
carries a multidimensional array, or a tensor.

Tensors are the basic data structures in TensorFlow. They are defined as N-dimensional arrays or lists of values, where N can be
any non-negative integer. Tensors have a shape and a data type (dtype), which specify the number and size of dimensions, and the type
of values stored in the tensor, respectively.

There are different types of tensors in TensorFlow, depending on their rank (number of dimensions), shape (size of each dimension), 
and values. Some of the common types of tensors are:

- Scalar: A tensor with rank 0, i.e., a single value. For example, tf.constant(42) is a scalar tensor.
- Vector: A tensor with rank 1, i.e., a list of values. For example, tf.constant([1, 2, 3]) is a vector tensor.
- Matrix: A tensor with rank 2, i.e., a list of lists of values. For example, tf.constant([[1, 2], [3, 4]]) is a matrix tensor.
- Tensor: A tensor with rank 3 or higher, i.e., a list of lists of lists of values (or higher-order lists). For example, 
  tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) is a tensor with rank 3.

Tensors can be created from various sources, such as constants, variables, placeholders, operations, or data files.
Tensors can also be converted to other data structures, such as NumPy arrays or Python lists.
Tensors can be manipulated by applying various operations on them, such as arithmetic operations, slicing and indexing, 
reshaping and transposing, reducing and aggregating, etc.

In [ ]:
Q2.How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example?

In [ ]:
The main difference between TensorFlow constants and variables is that constants are immutable and variables are mutable. 
This means that once you create a constant tensor, you cannot change its value or shape, while you can update a variable tensor with
new values or shapes using methods such as tf.assign or tf.Variable.assign.

Another difference is that constants are initialized with values, not operations, while variables can be initialized with either 
values or operations. For example, you can create a constant tensor with tf.constant(42), but not with tf.constant(tf.add(1, 2)).
However, you can create a variable tensor with tf.Variable(42) or with tf.Variable(tf.add(1, 2)).

A third difference is that constants are stored in the graph definition, while variables are stored separately in memory. 
This means that constants take up more space in the graph, and can cause memory issues if they are large. Variables, 
on the other hand, are more efficient in terms of memory usage, and can be saved and restored using checkpoints.

To use variables in TensorFlow, you need to initialize them first using methods such as tf.global_variables_initializer or 
tf.variables_initializer. These methods create operations that assign the initial values to the variables. 
You need to run these operations in a session before using the variables in other operations. Constants, on the other hand, 
do not need to be initialized, and can be used directly in the graph.

In [ ]:
Q3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

In [ ]:
Matrix addition, multiplication, and element-wise operations are common operations in linear algebra and TensorFlow provides various 
functions to perform them on tensors.

Matrix addition is the operation of adding two matrices of the same shape by adding the corresponding elements of each matrix. 
For example, if A and B are two matrices of shape (m, n), then their sum C is also a matrix of shape (m, n)
such that C[i, j] = A[i, j] + B[i, j] for all i and j. In TensorFlow, matrix addition can be done using the function tf.add or 
the operator +. For example:

In [4]:
!pip install tensorflow

In [5]:
import tensorflow as tf

# Create two matrices of shape (2, 3)
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[7, 8, 9], [10, 11, 12]])

# Add the matrices element-wise
C = tf.add(A, B) # or C = A + B

# Print the result
print(C)

tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


In [ ]:
Matrix multiplication is the operation of multiplying two matrices of compatible shapes by multiplying the rows of the first matrix
with the columns of the second matrix and summing up the products. For example, if A is a matrix of shape (m, n) and B is a matrix 
of shape (n, p), then their product C is a matrix of shape (m, p) such that C[i, j] = sum(A[i, k] * B[k, j]) for all i and j.
In TensorFlow, matrix multiplication can be done using the function tf.linalg.matmul or the operator. For example:

In [6]:
import tensorflow as tf

# Create two matrices of shape (2, 3) and (3, 2)
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[7, 8], [9, 10], [11, 12]])

# Multiply the matrices
C = tf.linalg.matmul(A, B) # or C = A @ B

# Print the result
print(C)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [ ]:
Element-wise operations are operations that apply a function to each element of a matrix or a tensor. For example, 
element-wise square is the operation of squaring each element of a matrix or a tensor. In TensorFlow, element-wise operations can be
done using various functions such as tf.square, tf.exp, tf.sin, etc. For example:

In [7]:
import tensorflow as tf

# Create a matrix of shape (2, 3)
A = tf.constant([[1, 2, 3], [4, 5, 6]])

# Square each element of the matrix
B = tf.square(A)

# Print the result
print(B)

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


### Part 2: Practical Implementation

#### Task 1: Creating and Manipulating Matrices

In [ ]:
1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A.
2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B.
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [8]:
# 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.
A = tf.random.normal(shape=(2, 2))
print("Matrix A:")
print(A)

Matrix A:
tf.Tensor(
[[ 2.433852   -0.9320342 ]
 [-0.3646633  -0.74187094]], shape=(2, 2), dtype=float32)


In [9]:
# 2. Create a Gaussian matrix B with dimensions 2x2, using TensorFlow's truncated_normal function. Display the values of matrix B.
B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B:")
print(B)

Matrix B:
tf.Tensor(
[[ 0.8802337  -0.08520655]
 [ 0.737301   -0.08220853]], shape=(2, 2), dtype=float32)


In [10]:
# 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard 
#deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.5)
print("Matrix C:")
print(C)

Matrix C:
tf.Tensor(
[[1.2074707 1.4678328]
 [1.6818638 1.8952678]], shape=(2, 2), dtype=float32)


In [11]:
# 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
D = tf.add(A, B)
print("Matrix D:")
print(D)

Matrix D:
tf.Tensor(
[[ 3.3140857  -1.0172408 ]
 [ 0.3726377  -0.82407945]], shape=(2, 2), dtype=float32)


In [12]:
# 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
E = tf.matmul(C, D)
print("Matrix E:")
print(E)

Matrix E:
tf.Tensor(
[[ 4.548631  -2.437899 ]
 [ 6.280089  -3.2727118]], shape=(2, 2), dtype=float32)


### Talk 2: Performing Additional Matrix Operations

In [ ]:
1.Create a matrix F with dimensions 2x2, initialized with random values using TensorFlows random_uniform function.
2.Calculate the transpose of matrix F and store the result in matrix G.
3.Calculate the elementwise exponential of matrix F and store the result in matrix H.
4.Create a matrix I by concatenating matrix F and matrix G horizontally.
5.Create a matrix J by concatenating matrix F and matrix H vertically.

In [13]:
import tensorflow as tf

In [14]:
# 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.
F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(F)

Matrix F:
tf.Tensor(
[[0.97545874 0.57574785]
 [0.1288836  0.78447556]], shape=(2, 2), dtype=float32)


In [15]:
# 2. Calculate the transpose of matrix F and store the result in matrix G.
G = tf.transpose(F)
print("Matrix G:")
print(G)

Matrix G:
tf.Tensor(
[[0.97545874 0.1288836 ]
 [0.57574785 0.78447556]], shape=(2, 2), dtype=float32)


In [16]:
# 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.
H = tf.exp(F)
print("Matrix H:")
print(H)

Matrix H:
tf.Tensor(
[[2.6523838 1.77846  ]
 [1.1375577 2.1912575]], shape=(2, 2), dtype=float32)


In [17]:
# 4. Create a matrix I by concatenating matrix F and matrix G horizontally.
I = tf.concat([F, G], axis=1)
print("Matrix I:")
print(I)

Matrix I:
tf.Tensor(
[[0.97545874 0.57574785 0.97545874 0.1288836 ]
 [0.1288836  0.78447556 0.57574785 0.78447556]], shape=(2, 4), dtype=float32)


In [18]:
# 5. Create a matrix J by concatenating matrix F and matrix H vertically.
J = tf.concat([F, H], axis=0)
print("Matrix J:")
print(J)

Matrix J:
tf.Tensor(
[[0.97545874 0.57574785]
 [0.1288836  0.78447556]
 [2.6523838  1.77846   ]
 [1.1375577  2.1912575 ]], shape=(4, 2), dtype=float32)
